### PR TITLE
fluidlite support

### PR DESCRIPTION
**Pull request by netpipe**
had a freelancer build this for us. works on windows and linux might need to fix the openal path in one spot to make it compile on windows again.

### CODE REVIEW

**Comment by karawitan** [comment]
Some files should be removed from commit: Examples/Tutorial10Fluidlite/CMakeFiles/Tutorial1_3DSound.dir/src/main.cpp.o

**Comment by netpipe** [comment]
fixed, thanks.

**Comment by netpipe** [comment]
hmmm maybe i never needed to modify so many files, the example seems to compile with stock caudio. just need the cb files with it

**Comment by r4stl1n** [comment]
This is a large amount of files to review with their changes. If you could clean up the commit to only the files necessary to implement support i would be willing to pull it in

**Comment by karawitan** [comment]
@netpipe, I'm not an expert at cmake, but these files are good candidates for removal as well;

```
bash-5.1$ grep  -rl "CMAKE generated file: DO NOT EDIT" .
./Examples/Tutorial10Fluidlite/CMakeFiles/Tutorial1_3DSound.dir/depend.internal
./Examples/Tutorial10Fluidlite/CMakeFiles/Tutorial1_3DSound.dir/depend.make
./Examples/Tutorial10Fluidlite/CMakeFiles/Tutorial1_3DSound.dir/build.make
./Examples/Tutorial10Fluidlite/CMakeFiles/Tutorial1_3DSound.dir/flags.make
./Examples/Tutorial10Fluidlite/CMakeFiles/CMakeDirectoryInformation.cmake
./Examples/Tutorial10Fluidlite/Makefile

```
Additionnally or as an alternative, If you're using cmake 3, you might call the "clean" target

`cmake --build C:/foo/build/ --target clean`

**Pull request closed without merging**
